### PR TITLE
Update sslocal via an OTA service

### LINKED ISSUE #1332: Binary for arm architecture macOS
Since Apple has released an arm architecture macOS, ShadowsocksX-NG should also release a binary for those users. (Even though x86 apps are still supported on those machines.)

*Problems*

The repo contains a x86 binary of `shadowsocks-libev`. It’s even copied from HomeBrew a long time ago!

*Possible solutions*

1. Build shadowsocks from source. **(RECOMMEND, by embedding a build script.)**
2. Include another arm binary.

### PR DESCRIPTION
**Pull request by yikerman**
Fix #1332.

### CODE REVIEW

**Comment by yikerman** [comment]
Oh wait there seems to be a few bugs.

**Comment by xiaoyu2006** [comment]
Seems to work now.

**Comment by yikerman** [comment]
Should work now.

**Comment by yikerman** [comment]
***CHANGES***

 - Introduce a new menu entry for updating the prebuilt universal `sslocal` binary from the [repo](https://github.com/ssx-ng/ss-buildbot).

截屏2021-02-03 下午9 00 20

> If you don't trust me, feel free to copy the repo.

**Comment by yikerman** [comment]
Nah let’s do it ourselves.

https://github.com/ssx-ng/ShadowsocksX-NG

**Comment by gaga227** [comment]
dear friends&nbsp; &nbsp;
&nbsp; &nbsp;Can you read chinese? I want to buy&nbsp;your shadowsocks Code. But I need to see the demo. Can you give me a demo？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadowsocks/ShadowsocksX-NG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 凌晨0:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [shadowsocks/ShadowsocksX-NG] Update sslocal via an OTA service (#1367)





 
Nah let’s do it ourselves.

**Comment by yikerman** [comment]
@gaga227 Leave your email for contacting.

Note that all of my work is open-sourced and you don’t need to purchase it. However, I’m happy to receive donations.

**Comment by gaga227** [comment]
就是这个邮箱&nbsp; 就可以联系到我


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadowsocks/ShadowsocksX-NG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 中午1:26
***@***.***&gt;;
抄送:&nbsp;"        ***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadowsocks/ShadowsocksX-NG] Update sslocal via an OTA service (#1367)





 
@gaga227 Leave your email for contacting.

**Comment by yikerman** [comment]
@gaga227 I can’t see your email.

**Comment by yikerman** [comment]
@gaga227 Mail to me use [caoyi06@qq.com](mailto:caoyi06@qq.com)

**Pull request closed without merging**
