### PR TITLE
Project skeleton optimization

### PR DESCRIPTION
**Pull request by cs17899219**
1. Removed temporary files and local generated files by using "gitignore".

### CODE REVIEW

**Comment by qiuyuzhou** [comment]
即使要避免提交pods到git，Podfile.lock必须加入git。

Whether or not you check in the Pods directory, the Podfile and Podfile.lock should always be kept under version control.

[What is Podfile.lock](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-podfilelock)

**Comment by qiuyuzhou** [comment]
我尝试了merge，任然有问题。合并后，我执行pod install后，工程文件中build phases会出现重复跟pod有关步骤。一些是以[cp]开头，一些是以📦开头。你使用的是cocoapod的app吗？如果是请使用命令行版本更新到最新的1.0.1，app只有1.0版本。

**Comment by qiuyuzhou** [comment]
我觉得commit Pods目录不是什么问题。暂时就不用做改变了。
文档中也推荐将Pods目录提交到版本控制系统。

Whether or not you check in your Pods folder is up to you, as workflows vary from project to project. We recommend that you keep the Pods directory under source control, and don't add it to your .gitignore. But ultimately this decision is up to you:

不管怎样，感谢你工作。

**Comment by qiuyuzhou** [comment]
已手工将你的.gitignore除了Pods以外的内容加入。

Thanks

**Comment by cs17899219** [comment]
Thank you very much. I will fix my project by rebase you branch.

**Comment by cs17899219** [comment]
Additionally, The version of Pod on travis-ci is very low. May cause problem when build the project on CI.

https://travis-ci.org/qiuyuzhou/ShadowsocksX-NG
$ pod --version
0.39.0

**Comment by qiuyuzhou** [comment]
因为已经提交所有Pods文件到git，所以无需依赖于travis上的pod安装依赖包。在 2016年6月14日，上午11:11，cs17899219 <notifications@github.com> 写道：Additionally, The version of Pod on travis-ci is very low. May cause problem when build the project on CI.https://travis-ci.org/qiuyuzhou/ShadowsocksX-NG
$ pod --version
0.39.0—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cs17899219** [comment]
OK, thanks.

**Pull request closed without merging**
